_wandb:
    value:
        cli_version: 0.19.5
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 19
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.5
            "8":
                - 5
            "12": 0.19.5
            "13": linux-x86_64
architecture:
    value: DQN
clip_ratio:
    value: 0.2
epochs:
    value: 500
learning_rate:
    value: 0.0001
monitor_gym:
    value: true
pi_lr:
    value: 0.0003
vf_lr:
    value: 0.001
